version: 2

updates:
  # API NPM
  - package-ecosystem: npm
    directory: '/packages/api'
    schedule:
      interval: weekly
      time: '00:00'
      reviewers:
        - stuft2
      assignees:
        - stuft2
      commit-message:
        prefix: fix
        prefix-development: chore
        include: scope

  # Client NPM
  - package-ecosystem: npm
    directory: '/packages/client'
    schedule:
      interval: weekly
      time: '00:00'
    reviewers:
      - stuft2
    assignees:
      - stuft2
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
