version: 2

updates:
  # API NPM
  - package-ecosystem: npm
    directory: '/packages/api'
    schedule:
      interval: weekly
    target-branch: main
    reviewers:
      - stuft2

  # Client NPM
  - package-ecosystem: npm
    directory: '/packages/client'
    schedule:
      interval: weekly
    target-branch: main
    reviewers:
      - stuft2
