version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE_NAME}
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        port: ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    environment:
      DEBUG: ${DEBUG}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_ADDRESS: mongo # use service name only in docker compose
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
  admin:
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
