version: '3'
services:
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        port: ${PORT}
    ports:
      - ${PORT}:${PORT}
    links:
      - db
    environment:
      DEBUG: ${DEBUG}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_ADDRESS: db # use service name only in docker compose
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
  db:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE_NAME}
